# Generated by Django 4.0.2 on 2022-02-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('tag_line', models.CharField(blank=True, max_length=200, null=True)),
                ('btn_txt', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images')),
                ('image_caption', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
    ]
