# Generated by Django 4.0.2 on 2022-02-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_statistic_userprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='active_case_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='awards_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='successful_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='total_case_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
