# Generated by Django 4.0.2 on 2022-02-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_statistic_active_case_text_statistic_awards_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='active_case',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='active_case_text',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='awards_text',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='successful',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='successful_text',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='total_case',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='total_case_text',
        ),
        migrations.AddField(
            model_name='statistic',
            name='field_four',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name of Field Four'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='field_one',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name of Field One'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='field_three',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name of Field Three'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='field_two',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name of Field Two'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='number_four',
            field=models.IntegerField(default=0, verbose_name='Enter Number For Field Four'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='number_one',
            field=models.IntegerField(default=0, verbose_name='Enter Number For Field One'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='number_three',
            field=models.IntegerField(default=0, verbose_name='Enter Number For Field Three'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='number_two',
            field=models.IntegerField(default=0, verbose_name='Enter Number For Field Two'),
        ),
    ]
