# Generated by Django 4.0.2 on 2022-02-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_choose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choose',
            name='class_name',
            field=models.CharField(blank=True, default='icon-box-clr-1', max_length=50, null=True, verbose_name='Write a Class Name for Styling'),
        ),
    ]
