# Generated by Django 4.0.2 on 2022-02-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_choose_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='choose',
            name='class_name_icon',
            field=models.CharField(blank=True, default='fas fa-user-friends', max_length=50, null=True, verbose_name='Write a Class Name for Change Icon'),
        ),
        migrations.AlterField(
            model_name='choose',
            name='class_name',
            field=models.CharField(blank=True, default='icon-box-clr-1', max_length=50, null=True, verbose_name='Write a Class Name for Change Card Color'),
        ),
    ]
