# Generated by Django 4.0.2 on 2022-02-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='heading_one',
            field=models.CharField(blank=True, default='Get a Appointment Today!', max_length=50, null=True, verbose_name='Write a Heading For First Card'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='heading_two',
            field=models.CharField(blank=True, default='We Are The Best Choice For Your Case', max_length=50, null=True, verbose_name='Write a Heading For Second Card'),
        ),
    ]
