# Generated by Django 4.0.2 on 2022-02-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_appointment_heading_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='btn_text',
            field=models.CharField(blank=True, default='Get Appointment', max_length=15, null=True, verbose_name='Write a Button Text'),
        ),
    ]
