# Generated by Django 4.0.2 on 2022-02-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_appointment_btn_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonial_images', verbose_name='Upload an Image of Client')),
                ('quote', models.CharField(blank=True, max_length=200, null=True, verbose_name='Write a Quote/Good Words of Client')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Write Name of Client')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
