# Generated by Django 4.0.2 on 2022-02-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='class_name',
            field=models.CharField(blank=True, default='anim1', max_length=50, null=True, verbose_name='Write a Class Name for Change Card Color'),
        ),
    ]
