# Generated by Django 4.0.2 on 2022-02-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='admin_images', verbose_name='Upload an Image of Admin'),
        ),
    ]
