# Generated by Django 4.0.2 on 2022-02-22 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_alter_blog_options_remove_blog_timestamp_blog_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image_two',
            new_name='admin_image',
        ),
    ]
