# Generated by Django 4.0.2 on 2022-02-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_rename_image_two_blog_admin_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='Dhaka, Bangladesh', max_length=50, null=True, verbose_name='Set An Address')),
                ('call', models.CharField(blank=True, max_length=50, null=True, verbose_name='Set Phone Number')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Set Email')),
                ('support', models.CharField(blank=True, max_length=50, null=True, verbose_name='Set Support Email')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Section Info',
                'verbose_name_plural': 'Contacts Section Info',
            },
        ),
    ]
